{include file="sections/header.tpl"}
<style>
    /* Styles for overall layout and responsiveness */
    body {
        background-color: #f8f9fa;
        font-family: 'Arial', sans-serif;
        padding: 0;
        margin: 0;
    }

    .container {
        margin-top: 20px;
        background-color: #d8dfe5;
        border-radius: 8px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        padding: 20px;
        max-width: 98%;
        overflow-x: auto;
        flex-wrap: wrap;
        justify-content: space-between;
        align-items: center;
    }

    /* Styles for table and pagination */
    .table {
        width: 100%;
        margin-bottom: 1rem;
        background-color: #fff;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    }

    .table th {
        vertical-align: middle;
        border-color: #dee2e6;
        background-color: #343a40;
        color: #fff;
    }

    .table td {
        vertical-align: middle;
        border-color: #dee2e6;
    }

    .table-striped tbody tr:nth-of-type(odd) {
        background-color: rgba(0, 0, 0, 0.05);
    }

    .table-hover tbody tr:hover {
        background-color: rgba(0, 0, 0, 0.075);
        color: #333;
        font-weight: bold;
        transition: background-color 0.3s, color 0.3s;
    }

    .pagination .page-item .page-link {
        color: #007bff;
        background-color: #fff;
        border: 1px solid #dee2e6;
        margin: 0 2px;
        padding: 6px 12px;
        transition: background-color 0.3s, color 0.3s;
    }

    .pagination .page-item .page-link:hover {
        background-color: #e9ecef;
        color: #0056b3;
    }

    .pagination .page-item.active .page-link {
        z-index: 1;
        color: #fff;
        background-color: #007bff;
        border-color: #007bff;
    }

    .dataTables_wrapper .dataTables_paginate .paginate_button {
        display: inline-block;
        padding: 5px 10px;
        margin-right: 5px;
        border: 1px solid #ccc;
        background-color: #fff;
        color: #333;
        cursor: pointer;
    }

    .hidden-field {
        display: none;
    }
</style>
<style>
    .btn-group-flex {
        display: flex;
        justify-content: center;
        gap: 10px;
        flex-wrap: wrap;
    }

    .btn-group-flex .btn {
        flex: 1 1 auto;
        /* Allow buttons to shrink/grow as needed */
        max-width: 150px;
        /* Optional: Limit button width */
    }
</style>

<form id="" method="post" action="{$_url}plugin/hotspot_token">
    <div class="input-group">
        <div class="input-group-addon">
            <a href=""><span class="fa fa-refresh"></span></a>
        </div>
        <input type="text" name="search" class="form-control" value="{$search}" placeholder="{Lang::T('Search')}...">
        <div class="input-group-btn">
            <button class="btn btn-success" type="submit">{Lang::T('Search')}</button>
        </div>
    </div>
</form>
<form method="get" action="{$_url}plugin/hotspot_token">
    <!-- এই নিচের লাইন দুটি অবশ্যই যোগ করবেন -->
    <input type="hidden" name="_route" value="plugin/hotspot_token">
    
    <div class="row" style="background: #f4f4f4; padding: 15px; border-radius: 5px; margin-bottom: 15px;">
    <div class="row" style="background: #f4f4f4; padding: 15px; border-radius: 5px; margin-bottom: 15px;">
        <!-- Search Field -->
        <div class="col-md-3">
            <label>Search PIN/Serial</label>
            <input type="text" name="search" class="form-control" value="{$search}" placeholder="Search...">
        </div>

        <!-- Generated By (Admin & Resellers) Filter -->
<div class="col-md-2">
    <label><i class="fa fa-users"></i> Generated By</label>
    <select name="reseller_id" class="form-control">
        <option value="">-- All Users --</option>
        
        <!-- অ্যাডমিনদের লিস্ট -->
        <optgroup label="System Admins">
            {foreach ORM::for_table('tbl_users')->find_many() as $adm}
                <option value="{$adm['id']}" {if $smarty.get.reseller_id == $adm['id']}selected{/if}>
                    {$adm['fullname']} (Admin)
                </option>
            {/foreach}
        </optgroup>

        <!-- রেসেলারদের লিস্ট -->
        <optgroup label="Hotspot Resellers">
            {foreach ORM::for_table('tbl_hotspot_resellers')->find_many() as $reseller}
                <option value="{$reseller['id']}" {if $smarty.get.reseller_id == $reseller['id']}selected{/if}>
                    {$reseller['fullname']} (Reseller)
                </option>
            {/foreach}
        </optgroup>
    </select>
</div>

        <!-- Status Filter -->
        <div class="col-md-2">
            <label>Status</label>
            <select name="status" class="form-control">
                <option value="">-- All Status --</option>
                <option value="not_used" {if $smarty.get.status == 'not_used'}selected{/if}>Not Used</option>
                <option value="active" {if $smarty.get.status == 'active'}selected{/if}>Active (In Use)</option>
                <option value="used" {if $smarty.get.status == 'used'}selected{/if}>Expired/Used</option>
            </select>
        </div>

        <!-- Plan Filter -->
        <div class="col-md-3">
            <label>Internet Plan</label>
            <select name="plan_id" class="form-control">
                <option value="">-- All Plans --</option>
                {foreach ORM::for_table('tbl_plans')->where('type','Hotspot')->find_many() as $p}
                    <option value="{$p['id']}" {if $smarty.get.plan_id == $p['id']}selected{/if}>
                        {$p['name_plan']}
                    </option>
                {/foreach}
            </select>
        </div>

        <!-- Filter Button -->
        <div class="col-md-2">
            <label>&nbsp;</label>
            <button type="submit" class="btn btn-primary btn-block">
                <i class="fa fa-filter"></i> Apply Filter
            </button>
        </div>
    </div>
</form>
<div class="row" style="padding: 5px">
    <div class="col-lg-3 col-lg-offset-0">
        <div class="btn-group btn-group-justified" role="group">

            <div class="btn-group" role="group">
                <a href="javascript:void(0)" 
                   onclick="printByPlan()" 
                   class="btn btn-info">
                    <i class="ion ion-android-print"></i> Print Filtered
                </a>
            </div>

            <div class="btn-group" role="group">
                <button type="button" 
                        onclick="deleteByPlan()" 
                        class="btn btn-danger">
                    <i class="glyphicon glyphicon-trash"></i> Delete Filtered
                </button>
            </div>

        </div>
    </div>
</div>


<!-- <div class="btn-group pull-left">
    <button class="btn btn-success btn-xs" data-toggle="modal" data-target="#settings" title="General Settings"><span
         class="glyphicon glyphicon-cog" aria-hidden="true"></span> {Lang::T('Settings')}</button>
</div> -->
<!-- token -->
<div class="row" style="padding: 5px">
    <div class="col-lg-3 col-lg-offset-9">
        <div class="btn-group btn-group-justified" role="group">
            <div class="btn-group" role="group">
                <a href="#" class="btn btn-primary" data-toggle="modal" data-target="#create">
                    {Lang::T('Generate Tokens')}</a>
            </div>
            <div class="btn-group" role="group">
                <a href="{$_url}plugin/hotspot_tokens_print" target="print_token" class="btn btn-info">
    <i class="ion ion-android-print"></i> Print All
</a>
            </div>
        </div>
    </div>
</div>
<div class="panel panel-hovered mb20 panel-primary">
    <div class="panel-heading">
        <!-- {if in_array($_admin['user_type'],['SuperAdmin','Admin'])}
        <div class="btn-group pull-right">
            <a class="btn btn-danger btn-xs" title="Remove used token" href="{$_url}plugin/hotspot_token"
                onclick="return confirm('Delete all used token code?')"><span class="glyphicon glyphicon-trash"
                    aria-hidden="true"></span> Delete All</a>
        </div>
        {/if} -->
        &nbsp;
    </div>


    <div class="container">
<table id="datatable" class="table table-bordered table-striped table-condensed">

<thead>
<tr>
    <th width="30">
    <input type="checkbox" id="checkAll">
</th>
    <th>{Lang::T('Token PIN')}</th>
    <th>{Lang::T('Token Price')}</th>
    <th>{Lang::T('Token Plan')}</th>

    <!-- Mbps -->
    <th>{Lang::T('Token Mbps')}</th>

    <th>{Lang::T('Token Status')}</th>
    <th>{Lang::T('Token Serial No')}</th>
    <th>{Lang::T('Created Date')}</th>
    <th>{Lang::T('Generated By')}</th>
    <th>{Lang::T('Used Date')}</th>
    <th>{Lang::T('Last Used')}</th>
    <th>{Lang::T('Usage Count')}</th>
    <th>{Lang::T('Used By')}</th>
</tr>
</thead>

<tbody>

{if $tokens}
{foreach $tokens as $token}

<tr>
    <td>
    <input type="checkbox" class="tokenCheckbox" name="checked_tokens[]" value="{$token['id']}">
</td>

<!-- PIN -->
<td style="background-color:black;color:black;"
    onmouseenter="this.style.backgroundColor='white';"
    onmouseleave="this.style.backgroundColor='black';">
    {$token['token_number']}
</td>

<!-- PRICE -->
<td>{$token['value']}</td>

<!-- PLAN -->
<td>
    {if isset($token['name_plan']) && $token['name_plan'] != ''}
        <span class="label label-info">
            {$token['name_plan']}
        </span>
    {else}
        <span class="label label-default">No Plan</span>
    {/if}
</td>

<!-- ✅ MBPS FIXED -->
<td>
    {if isset($token['name_bw']) && $token['name_bw'] != ''}
        <span class="label label-success">

            {$token['name_bw']}
            <br>

            {$token['rate_down']}{$token['rate_down_unit']}
            /
            {$token['rate_up']}{$token['rate_up_unit']}

        </span>
    {else}
        <span class="label label-default">
            N/A
        </span>
    {/if}
</td>

<!-- STATUS -->
<td>
    {if $token['status'] == 'used'}
        <span class="label label-danger">Used</span>
    {elseif $token['status'] == 'active'}
        <span class="label label-warning">Active</span>
    {else}
        <span class="label label-success">Not Used</span>
    {/if}
</td>

<!-- SERIAL -->
<td style="background-color:black;color:black;"
    onmouseenter="this.style.backgroundColor='white';"
    onmouseleave="this.style.backgroundColor='black';">
    {$token['serial_number']}
</td>

<!-- CREATED -->
<td>{$token['created_at']}</td>

<!-- GENERATED BY -->
<td>
    {if $token.reseller_id > 0 && $token.reseller_name != ''}
    <span class="label label-success">
        {$token.reseller_name}
    </span>
{else}
    <span class="label label-primary">
        {$token.admin_name}
    </span>
{/if}
</td>

<!-- USED DATE -->
<td>{$token['first_used']}</td>

<!-- LAST USED -->
<td>{$token['last_used']}</td>

<!-- COUNT -->
<td>{$token['used_count']}</td>

<!-- USED BY -->
<td>
    {if $token['used_by']}
        {$token['used_by']}
    {else}
        None
    {/if}
</td>

</tr>

<!-- ACTION ROW -->
<tr>
<td colspan="12" style="text-align:center;">
    <div style="display:flex;justify-content:center;gap:10px;flex-wrap:wrap;">

        {if $token['status'] neq 'used'}
        <a href="{$_url}plugin/hotspot_tokens_print&token_id={$token['id']}"
           class="btn btn-success btn-xs">
            {Lang::T('Print')}
        </a>
        {/if}

        <button type="button"
                class="btn btn-primary btn-xs send-token"
                data-id="{$token['id']}"
                data-toggle="modal"
                data-target="#sendTokenModal">
            {Lang::T('Send')}
        </button>

        <button type="button"
                class="btn btn-warning btn-xs refill-token"
                data-id="{$token['id']}"
                data-toggle="modal"
                data-target="#refillTokenModal">
            {Lang::T('Refill')}
        </button>

        {if $token['status'] neq 'blocked'}
        <a href="javascript:void(0);"
           onclick="confirmAction('{$_url}plugin/hotspot_tokens_status&token_id={$token['id']}&status=blocked&csrf_token={$csrf_token}','Block')"
           class="btn btn-danger btn-xs">
            Block
        </a>
        {else}
        <a href="javascript:void(0);"
           onclick="confirmAction('{$_url}plugin/hotspot_tokens_status&token_id={$token['id']}&status=active&csrf_token={$csrf_token}','Unblock')"
           class="btn btn-warning btn-xs">
            Unblock
        </a>
        {/if}

        <a href="{$_url}plugin/hotspot_tokens_details&token_id={$token['id']}&csrf_token={$csrf_token}"
           class="btn btn-info btn-xs">
            More Info
        </a>

    </div>
</td>
</tr>

{/foreach}
{else}
<tr>
    <td colspan="12" style="text-align:center;">
        {Lang::T('No tokens found.')}
    </td>
</tr>
{/if}

</tbody>
</table>

{include file="pagination.tpl"}
</div>
</div>
        <div class="row" style="padding: 5px">
            <div class="col-lg-3 col-lg-offset-9">
                <div class="btn-group btn-group-justified" role="group">
                    <div class="btn-group" role="group">
                        {if in_array($_admin['user_type'],['SuperAdmin','Admin'])}
                        
                        {/if}
                    </div>
                    <div class="btn-group" role="group">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    &nbsp;

</div>

<div class="modal fade" id="settings">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"> {Lang::T('Generate Settings')}</h4>
            </div>
            <div class="box-body">
                <div class="tab-pane">
                    <form class="form-horizontal" method="post" autocomplete="off" role="form" action="">
                        <div class="form-group">
                            <label class="col-md-2 control-label">{Lang::T('Enable Recharge')}</label>
                            <div class="col-md-6">
                                <label class="switch">
                                    <input type="checkbox" id="hotspot_tokens_mode" value="1" name="hotspot_tokens_mode"
                                        {if $_c['hotspot_tokens_mode']==1}checked{/if}>
                                    <span class="slider"></span>
                                </label>
                            </div>
                        </div>
                        <div class="form-group" id="recharge-type-group">
                            <label class="col-md-2 control-label">{Lang::T('Recharge Notification')}</label>
                            <div class="col-md-6">
                                <select class="form-control" name="hotspot_tokens_notify" id="hotspot_tokens_notify">
                                    <option value="1" {if $_c['hotspot_tokens_notify']=='1' }selected{/if}>
                                        {Lang::T('Enabled')}</option>
                                    <option value="0" {if $_c['hotspot_tokens_notify']=='0' }selected{/if}>
                                        {Lang::T('Disabled')}</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">{Lang::T('Enable Message')}</label>
                            <div class="col-md-6">
                                <label class="switch">
                                    <input type="checkbox" id="recharge_message" value="1" name="recharge_message" {if
                                        $_c['recharge_message']==1 }checked{/if}>
                                    <span class="slider"></span>
                                </label>
                            </div>
                        </div>
                        <div class="form-group" id="message-group">
                            <label class="col-md-2 control-label">{Lang::T('Send Via')}</label>
                            <div class="col-md-6">
                                <select class="form-control" name="recharge_message_via" id="recharge_message_via">
                                    <option value="sms" {if $_c['recharge']=='sms' }selected{/if}>
                                        {Lang::T('SMS')}</option>
                                    <option value="wa" {if $_c['recharge_message_via']=='wa' }selected{/if}>
                                        {Lang::T('WhatsApp')}</option>
                                    <option value="both" {if $_c['recharge_message_via']=='both' }selected{/if}>
                                        {Lang::T('Both')}</option>
                                </select>
                            </div>
                        </div>
                        <div class="form-group" id="message-content-group">
                            <label class="col-md-2 control-label">{Lang::T('Message')}</label>
                            <div class="col-md-6">
                                <textarea class="form-control" id="recharge_message_content"
                                    name="recharge_message_content"
                                    rows="6">{Lang::htmlspecialchars($_json[''])}</textarea>
                            </div>
                            <p class="help-block col-md-4">
                                <b>[[login_code]]</b> - {Lang::T('will replace customer login code')}.<br>
                                <b>[[package]]</b> - {Lang::T('will replace customer package name')}.<br>
                                <b>[[expiry]]</b> - {Lang::T('will replace customer package expiry date')}.<br>
                                <b>[[company]]</b> - {Lang::T('will replace your Company Name')}.<br>
                            </p>
                        </div>
                        <div class="form-group" id="">
                            <label class="col-md-2 control-label">{Lang::T('Recharge Send Template')}</label>
                            <div class="col-md-6">
                                <textarea rows="8" name="recharge_send" id="recharge_send"
                                    class="form-control">{Lang::htmlspecialchars($_json[''])}</textarea>
                            </div>
                            <p class="help-block col-md-4">
                                <b>[[code]]</b> - {Lang::T('will replace recharge code')}.<br>
                                <b>[[data]]</b> - {Lang::T('will replace recharge data limit')}.<br>
                                <b>[[validity]]</b> - {Lang::T('will replace recharge validity or duration')}.<br>
                                <b>[[company]]</b> - {Lang::T('will replace your Company Name')}.<br>
                            </p>
                        </div>

                        <div class="form-group" id="">
                            <label class="col-md-2 control-label">{Lang::T('Recharge Tokens Print Template')}</label>
                            <div class="col-md-6">
                                <textarea rows="8" name="" id=""
                                    class="form-control">{Lang::htmlspecialchars($_json[''])}</textarea>
                            </div>
                            <p class="help-block col-md-4">
                                <b>[[currency]]</b> - {Lang::T('will replace recharge currency code')}.<br>
                                <b>[[plan_price]]</b> - {Lang::T('will replace recharge plan price')}.<br>
                                <b>[[code]]</b> - {Lang::T('will replace recharge code')}.<br>
                                <b>[[data]]</b> - {Lang::T('will replace recharge data limit')}.<br>
                                <b>[[validity]]</b> - {Lang::T('will replace recharge validity or duration')}.<br>
                                <b>[[url]]</b> - {Lang::T('will replace recharge with recharge login url')}.<br>
                                <b>[[qrcode]]</b> - {Lang::T('will replace recharge QRcode')}.<br>
                            </p>
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                <button class="btn btn-success btn-block" name="save" value="save" type="submit">
                                    {Lang::T('Save Changes')}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<form id="printSelectedForm" method="POST" action="{$_url}plugin/hotspot_tokens_print">
    <input type="hidden" name="tokenIds" id="tokenIdsInput">
</form>

<div class="modal fade" id="create">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"> {Lang::T('Generate Tokens')}</h4>
            </div>
            <div class="box-body">
                <div class="tab-pane">
                    <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                        <div class="form-group">
                            <label for="inputExperience" class="col-sm-2 control-label">{Lang::T('No of
                                Tokens')}</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="number_of_tokens" value="1">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputSkills" class="col-sm-2 control-label">
                                {Lang::T('PIN Length')}</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="lengthcode" value="12">
                            </div>
                        </div>
<div class="form-group">
    <label class="col-sm-2 control-label">
        {Lang::T('Select Plan')}</label>
    <div class="col-sm-10">
        <select class="form-control" name="plan_id" id="plan_id" required>
    <option value="">-- Select Plan --</option>

    {foreach ORM::for_table('tbl_plans')->where('type','Hotspot')->find_many() as $p}
        <option value="{$p['id']}" data-price="{$p['price']}">
            {$p['name_plan']} - {$p['price']}
        </option>
    {/foreach}

</select>
    </div>
</div>

<input type="hidden" name="token_value" id="token_value">
                        <div class="form-group">
                            <label for="inputSkills" class="col-sm-2 control-label"> {Lang::T('Print
                                Now')}</label>

                            <div class="col-sm-10">
                                <input type="checkbox" id="print_now" name="print_now" class="iCheck" value="1">
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="pull-right">
                                <button type="submit" value="token" name="generate" class="btn btn-primary">
                                    <i class="fa fa-telegram">
                                    </i> {Lang::T('Generate')}</button>
                            </div>
                            <button type="button" data-dismiss="modal" class="btn btn-danger">
                                <i class="">
                                </i> {Lang::T('Cancel')}</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>




<!-- Send Token Modal HTML -->

<div class="modal fade" id="sendTokenModal" tabindex="-1" role="dialog" aria-labelledby="sendTokenLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="sendTokenLabel"> {Lang::T('Send Token PIN')}</h4>
            </div>
            <div class="box-body">
                <div class="tab-pane">
                    <form action="{$_url}plugin/hotspot_tokens_sendToken" method="post" enctype="multipart/form-data"
                        class="form-horizontal">
                        <input type="hidden" id="tokenId" name="tokenId">
                        <div class="form-group">
                            <label for="phone_number" class="col-sm-2 control-label">{Lang::T('Phone No')}</label>
                            <div class="col-sm-10">
                                <input type="text" id="phone_number" name="phoneNumber"
                                    placeholder="{Lang::T('Enter the receiver phone number')}" class="form-control">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="method" class="col-sm-2 control-label">{Lang::T('Send Via')}</label>
                            <div class="col-sm-10">
                                <select name="method" id="method" class="form-control">
                                    <option value="sms">{Lang::T('SMS')}</option>
                                    <option value="wa">{Lang::T('WhatsApp')}</option>
                                    <option value="both">{Lang::T('Both')}</option>
                                </select>
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="pull-right">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-telegram"></i> {Lang::T('Send Now')}
                                </button>
                            </div>
                            <button type="button" data-dismiss="modal" class="btn btn-danger">
                                <i class=""></i> {Lang::T('Cancel')}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Refill Token Modal HTML -->

<div class="modal fade" id="refillTokenModal" tabindex="-1" role="dialog" aria-labelledby="refillTokenLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="refillTokenLabel"> {Lang::T('Refill Token PIN')}</h4>
            </div>
            <div class="box-body">
                <div class="tab-pane">
                    <form action="{$_url}plugin/hotspot_tokens_refillToken" method="post" enctype="multipart/form-data"
                        class="form-horizontal">
                        <input type="hidden" id="tokenId" name="tokenId">
                        <div class="form-group">
                            <label for="amount" class="col-sm-2 control-label">{Lang::T('Amount')}</label>
                            <div class="col-sm-10">
                                <input type="text" id="amount" name="amount" placeholder="{Lang::T('Enter the amount')}"
                                    class="form-control">
                                <small>
                                    <input id="notify" name="notify" type="checkbox"> {Lang::T('Send Notification')}
                                </small>
                            </div>
                        </div>
                        <div class="form-group hidden-field" id="phoneNumberGroup">
                            <label for="phoneNumber" class="col-sm-2 control-label">{Lang::T('Phone No')}</label>
                            <div class="col-sm-10">
                                <input type="text" id="phoneNumber" name="phoneNumber"
                                    placeholder="{Lang::T('Enter the receiver phone number')}" class="form-control">
                            </div>
                        </div>
                        <div class="form-group hidden-field" id="methodGroup">
                            <label for="method" class="col-sm-2 control-label">{Lang::T('Send Via')}</label>
                            <div class="col-sm-10">
                                <select name="method" id="method" class="form-control">
                                    <option value="sms">{Lang::T('SMS')}</option>
                                    <option value="wa">{Lang::T('WhatsApp')}</option>
                                    <option value="both">{Lang::T('Both')}</option>
                                </select>
                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="pull-right">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-telegram"></i> {Lang::T('Refill')}
                                </button>
                            </div>
                            <button type="button" data-dismiss="modal" class="btn btn-danger">
                                <i class=""></i> {Lang::T('Cancel')}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    function deleteVouchers(voucherIds) {
        if (voucherIds.length > 0) {
            Swal.fire({
                title: 'Are you sure?',
                text: 'You won\'t be able to revert this!',
                icon: 'warning',
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'Cancel'
            }).then((result) => {
                if (result.isConfirmed) {
                    var xhr = new XMLHttpRequest();
                    xhr.open('POST', '{$_url}plugin/hotspot_tokens_delete', true);
                    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                    xhr.onload = function () {
                        if (xhr.status === 200) {
                            var response = JSON.parse(xhr.responseText);

                            if (response.status === 'success') {
                                Swal.fire({
                                    title: 'Deleted!',
                                    text: response.message,
                                    icon: 'success',
                                    confirmButtonText: 'OK'
                                }).then(() => {
                                    location.reload(); // Reload the page after confirmation
                                });
                            } else {
                                Swal.fire({
                                    title: 'Error!',
                                    text: response.message,
                                    icon: 'error',
                                    confirmButtonText: 'OK'
                                });
                            }
                        } else {
                            Swal.fire({
                                title: 'Error!',
                                text: 'Failed to delete tokens. Please try again.',
                                icon: 'error',
                                confirmButtonText: 'OK'
                            });
                        }
                    };
                    xhr.send('tokenIds=' + JSON.stringify(voucherIds));
                }
            });
        } else {
            Swal.fire({
                title: 'Error!',
                text: 'No tokens selected to delete.',
                icon: 'error',
                confirmButtonText: 'OK'
            });
        }
    }

    // Example usage for selected tokens
    document.getElementById('deleteSelectedTokens').addEventListener('click', function () {
        var selectedTokens = [];
        document.querySelectorAll('input[name="token_ids[]"]:checked').forEach(function (checkbox) {
            selectedTokens.push(checkbox.value);
        });

        if (selectedTokens.length > 0) {
            deleteVouchers(selectedTokens);
        } else {
            Swal.fire({
                title: 'Error!',
                text: 'Please select at least one token to delete.',
                icon: 'error',
                confirmButtonText: 'OK'
            });
        }
    });

    // Example usage for single token deletion
    document.querySelectorAll('.delete-token').forEach(function (button) {
        button.addEventListener('click', function () {
            var tokenId = this.getAttribute('data-id');
            deleteVouchers([tokenId]);
        });
    });


    // Select or deselect all checkboxes
    document.getElementById('select-all').addEventListener('change', function () {
        var checkboxes = document.querySelectorAll('input[name="token_ids[]"]');
        for (var checkbox of checkboxes) {
            checkbox.checked = this.checked;
        }
    });
</script>
{literal}
<script>
    function confirmAction(url, action) {
        Swal.fire({
            title: 'Are you sure?',
            text: `Do you really want to ${action.toLowerCase()} this token?`,
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, proceed!',
            cancelButtonText: 'No, cancel!'
        }).then((result) => {
            if (result.isConfirmed) {
                window.location.href = url;
            }
        });
    }
</script>
{/literal}
<script>
    const $q = jQuery.noConflict();

    $q(document).ready(function () {
        $q('#locktable').DataTable({
            "pagingType": "full_numbers",
            "order": [
                [1, 'desc']
            ]
        });
    });
</script>
<script>
    const $j = jQuery.noConflict();

    $j(document).ready(function () {
        $j('#datatable').DataTable({
            "pagingType": "full_numbers",
            "order": [
                [1, 'desc']
            ]
        });
    });
</script>
<script>
    document.getElementById('printSelectedTokens').addEventListener('click', function () {
        var selectedTokens = [];
        document.querySelectorAll('input[name="token_ids[]"]:checked').forEach(function (checkbox) {
            selectedTokens.push(checkbox.value);
        });

        if (selectedTokens.length > 0) {
            document.getElementById('tokenIdsInput').value = JSON.stringify(selectedTokens);
            document.getElementById('printSelectedForm').submit();
        } else {
            alert('Please select at least one token to print.');
        }
    });
</script>
<script>
    var $ = jQuery.noConflict();
    $(document).ready(function () {
        $('.send-token').on('click', function () {
            var tokenId = $(this).data('id');
            console.log('token ID:', tokenId);
            $('#sendTokenModal').find('#tokenId').val(tokenId); // Corrected ID reference
        });
    });
</script>
<script>
    var $ = jQuery.noConflict();
    $(document).ready(function () {
        $('.refill-token').on('click', function () {
            var tokenId = $(this).data('id');
            console.log('token ID:', tokenId);
            $('#refillTokenModal').find('#tokenId').val(tokenId); // Corrected ID reference
        });
    });
</script>
<script>
    document.getElementById('notify').addEventListener('change', function () {
        var phoneNumberGroup = document.getElementById('phoneNumberGroup');
        var methodGroup = document.getElementById('methodGroup');

        if (this.checked) {
            phoneNumberGroup.classList.remove('hidden-field');
            methodGroup.classList.remove('hidden-field');
        } else {
            phoneNumberGroup.classList.add('hidden-field');
            methodGroup.classList.add('hidden-field');
        }
    });
</script>


<script>
    window.addEventListener('DOMContentLoaded', function () {
        var portalLink = "#";
        $('#version').html('Recharge Tokens Plugin | Ver: 1.0 | by: <a href="' + portalLink + '">Dyrsia</a>');
    });
</script>
<!-- ├░┼╕тАЭ┬е DELETE SCRIPT -->
<script>
function deleteByType(type){
    Swal.fire({
        title: 'Are you sure?',
        text: 'This will delete tokens permanently!',
        icon: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Yes, delete'
    }).then((result) => {
        if(result.isConfirmed){

            fetch("{$_url}plugin/hotspot_tokens_delete&type=" + type)
            .then(res => res.json())
            .then(data => {
                Swal.fire(data.message, '', data.status);
                setTimeout(()=>location.reload(), 1200);
            });
        }
    });
}
</script>
<script>
var $ = jQuery.noConflict();

$(document).ready(function(){

    $('#plan_id').on('change', function(){
        var price = $(this).find(':selected').data('price');

        if(price){
            $('#token_value').val(price);
        }else{
            $('#token_value').val('');
        }
    });

});
</script>
<script>

function getSelectedTokens(){

    let selected = [];

    document.querySelectorAll('.tokenCheckbox:checked').forEach(function(el){
        selected.push(el.value);
    });

    return selected;
}


// =======================
// GET FILTER QUERY
// =======================
function getFilterQuery(){

    let params = new URLSearchParams();

    let search = document.querySelector('input[name="search"]');
    let plan = document.querySelector('select[name="plan_id"]');
    let status = document.querySelector('select[name="status"]');
    let reseller = document.querySelector('select[name="reseller_id"]');

    if(search && search.value !== ''){
        params.append('search', search.value);
    }

    if(plan && plan.value !== ''){
        params.append('plan_id', plan.value);
    }

    if(status && status.value !== ''){
        params.append('status', status.value);
    }

    if(reseller && reseller.value !== ''){
        params.append('reseller_id', reseller.value);
    }

    return params.toString();
}



// =======================
// PRINT FUNCTION
// =======================
function printByPlan(){

    let selectedTokens = getSelectedTokens();

    // ✅ PRINT SELECTED
    if(selectedTokens.length > 0){

        let form = document.createElement('form');

        form.method = 'POST';
        form.action = "{$_url}plugin/hotspot_tokens_print";
        form.target = "_blank";

        let input = document.createElement('input');

        input.type = 'hidden';
        input.name = 'tokenIds';
        input.value = JSON.stringify(selectedTokens);

        form.appendChild(input);

        document.body.appendChild(form);

        form.submit();

        document.body.removeChild(form);

        return;
    }

    // ✅ PRINT FILTERED
    let query = getFilterQuery();

    if(query === ''){

        Swal.fire(
            'Error',
            'Please apply filter OR select tokens',
            'error'
        );

        return;
    }

    let url =
        "{$_url}plugin/hotspot_tokens_print&type=filter&" + query;

    window.open(url, "_self");
}



// =======================
// DELETE FUNCTION
// =======================
function deleteByPlan(){

    let selectedTokens = getSelectedTokens();

    // ✅ DELETE SELECTED
    if(selectedTokens.length > 0){

        Swal.fire({
            title: 'Confirm Delete',
            text: 'Delete selected tokens?',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Yes Delete'
        }).then((result)=>{

            if(result.isConfirmed){

                fetch("{$_url}plugin/hotspot_tokens_delete",{
                    method:'POST',
                    headers:{
                        'Content-Type':'application/x-www-form-urlencoded'
                    },
                    body:'tokenIds=' + JSON.stringify(selectedTokens)
                })
                .then(res=>res.json())
                .then(data=>{

                    Swal.fire(data.message,'',data.status);

                    setTimeout(()=>{
                        location.reload();
                    },1200);

                });

            }

        });

        return;
    }


    // ✅ DELETE FILTERED
    let query = getFilterQuery();

    if(query === ''){

        Swal.fire(
            'Error',
            'Please apply filter OR select tokens',
            'error'
        );

        return;
    }

    Swal.fire({
        title: 'Confirm Delete',
        text: 'Delete filtered tokens?',
        icon: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Yes Delete'
    }).then((result)=>{

        if(result.isConfirmed){

            fetch(
                "{$_url}plugin/hotspot_tokens_delete&type=filter&" + query
            )
            .then(res=>res.json())
            .then(data=>{

                Swal.fire(data.message,'',data.status);

                setTimeout(()=>{
                    location.reload();
                },1200);

            });

        }

    });

}



// =======================
// CHECK ALL
// =======================
document.getElementById('checkAll').addEventListener('click', function(){

    let checkboxes = document.querySelectorAll('.tokenCheckbox');

    checkboxes.forEach(function(cb){

        cb.checked = document.getElementById('checkAll').checked;

    });

});

</script>

{include file="sections/footer.tpl"}